//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.08 at 10:32:01 PM CLST 
//


package cl.riesal.cotizaOnline.report;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cl.riesal.cotizaOnline.report package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cl.riesal.cotizaOnline.report
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Xml }
     * 
     */
    public Xml createXml() {
        return new Xml();
    }

    /**
     * Create an instance of {@link Xml.Productos }
     * 
     */
    public Xml.Productos createXmlProductos() {
        return new Xml.Productos();
    }

    /**
     * Create an instance of {@link Xml.Productos.Producto }
     * 
     */
    public Xml.Productos.Producto createXmlProductosProducto() {
        return new Xml.Productos.Producto();
    }

}
