//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.08 at 10:32:01 PM CLST 
//


package cl.riesal.cotizaOnline.report;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nCotizacion" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="fechaCotizacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreEmpresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rutEmpresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="direccionEmpresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="giroEmpresa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="plantel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="area" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="solicita" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="descripcionTrabajo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="valorManoObra" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="valorMateriales" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="valorTraslado" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="gastoOperacional" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="utilidad" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="totalNeto" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="productos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="producto" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="detalle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="neto" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nCotizacion",
    "fechaCotizacion",
    "nombreEmpresa",
    "rutEmpresa",
    "direccionEmpresa",
    "giroEmpresa",
    "plantel",
    "area",
    "solicita",
    "descripcionTrabajo",
    "valorManoObra",
    "valorMateriales",
    "valorTraslado",
    "gastoOperacional",
    "utilidad",
    "totalNeto",
    "productos"
})
@XmlRootElement(name = "xml")
public class Xml {

    protected short nCotizacion;
    @XmlElement(required = true)
    protected String fechaCotizacion;
    @XmlElement(required = true)
    protected String nombreEmpresa;
    @XmlElement(required = true)
    protected String rutEmpresa;
    @XmlElement(required = true)
    protected String direccionEmpresa;
    @XmlElement(required = true)
    protected String giroEmpresa;
    @XmlElement(required = true)
    protected String plantel;
    @XmlElement(required = true)
    protected String area;
    @XmlElement(required = true)
    protected String solicita;
    @XmlElement(required = true)
    protected String descripcionTrabajo;
    protected int valorManoObra;
    protected int valorMateriales;
    protected int valorTraslado;
    protected int gastoOperacional;
    protected int utilidad;
    protected int totalNeto;
    @XmlElement(required = true)
    protected Xml.Productos productos;

    /**
     * Gets the value of the nCotizacion property.
     * 
     */
    public short getNCotizacion() {
        return nCotizacion;
    }

    /**
     * Sets the value of the nCotizacion property.
     * 
     */
    public void setNCotizacion(short value) {
        this.nCotizacion = value;
    }

    /**
     * Gets the value of the fechaCotizacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFechaCotizacion() {
        return fechaCotizacion;
    }

    /**
     * Sets the value of the fechaCotizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFechaCotizacion(String value) {
        this.fechaCotizacion = value;
    }

    /**
     * Gets the value of the nombreEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreEmpresa() {
        return nombreEmpresa;
    }

    /**
     * Sets the value of the nombreEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreEmpresa(String value) {
        this.nombreEmpresa = value;
    }

    /**
     * Gets the value of the rutEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRutEmpresa() {
        return rutEmpresa;
    }

    /**
     * Sets the value of the rutEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRutEmpresa(String value) {
        this.rutEmpresa = value;
    }

    /**
     * Gets the value of the direccionEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionEmpresa() {
        return direccionEmpresa;
    }

    /**
     * Sets the value of the direccionEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionEmpresa(String value) {
        this.direccionEmpresa = value;
    }

    /**
     * Gets the value of the giroEmpresa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiroEmpresa() {
        return giroEmpresa;
    }

    /**
     * Sets the value of the giroEmpresa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiroEmpresa(String value) {
        this.giroEmpresa = value;
    }

    /**
     * Gets the value of the plantel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlantel() {
        return plantel;
    }

    /**
     * Sets the value of the plantel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlantel(String value) {
        this.plantel = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArea(String value) {
        this.area = value;
    }

    /**
     * Gets the value of the solicita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSolicita() {
        return solicita;
    }

    /**
     * Sets the value of the solicita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSolicita(String value) {
        this.solicita = value;
    }

    /**
     * Gets the value of the descripcionTrabajo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcionTrabajo() {
        return descripcionTrabajo;
    }

    /**
     * Sets the value of the descripcionTrabajo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcionTrabajo(String value) {
        this.descripcionTrabajo = value;
    }

    /**
     * Gets the value of the valorManoObra property.
     * 
     */
    public int getValorManoObra() {
        return valorManoObra;
    }

    /**
     * Sets the value of the valorManoObra property.
     * 
     */
    public void setValorManoObra(int value) {
        this.valorManoObra = value;
    }

    /**
     * Gets the value of the valorMateriales property.
     * 
     */
    public int getValorMateriales() {
        return valorMateriales;
    }

    /**
     * Sets the value of the valorMateriales property.
     * 
     */
    public void setValorMateriales(int value) {
        this.valorMateriales = value;
    }

    /**
     * Gets the value of the valorTraslado property.
     * 
     */
    public int getValorTraslado() {
        return valorTraslado;
    }

    /**
     * Sets the value of the valorTraslado property.
     * 
     */
    public void setValorTraslado(int value) {
        this.valorTraslado = value;
    }

    /**
     * Gets the value of the gastoOperacional property.
     * 
     */
    public int getGastoOperacional() {
        return gastoOperacional;
    }

    /**
     * Sets the value of the gastoOperacional property.
     * 
     */
    public void setGastoOperacional(int value) {
        this.gastoOperacional = value;
    }

    /**
     * Gets the value of the utilidad property.
     * 
     */
    public int getUtilidad() {
        return utilidad;
    }

    /**
     * Sets the value of the utilidad property.
     * 
     */
    public void setUtilidad(int value) {
        this.utilidad = value;
    }

    /**
     * Gets the value of the totalNeto property.
     * 
     */
    public int getTotalNeto() {
        return totalNeto;
    }

    /**
     * Sets the value of the totalNeto property.
     * 
     */
    public void setTotalNeto(int value) {
        this.totalNeto = value;
    }

    /**
     * Gets the value of the productos property.
     * 
     * @return
     *     possible object is
     *     {@link Xml.Productos }
     *     
     */
    public Xml.Productos getProductos() {
        return productos;
    }

    /**
     * Sets the value of the productos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Xml.Productos }
     *     
     */
    public void setProductos(Xml.Productos value) {
        this.productos = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="producto" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="detalle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="neto" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "producto"
    })
    public static class Productos {

        protected List<Xml.Productos.Producto> producto;

        /**
         * Gets the value of the producto property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the producto property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProducto().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Xml.Productos.Producto }
         * 
         * 
         */
        public List<Xml.Productos.Producto> getProducto() {
            if (producto == null) {
                producto = new ArrayList<Xml.Productos.Producto>();
            }
            return this.producto;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="numero" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="detalle" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="cantidad" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="valorUnitario" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="neto" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "numero",
            "detalle",
            "cantidad",
            "valorUnitario",
            "neto"
        })
        public static class Producto {

            protected int numero;
            @XmlElement(required = true)
            protected String detalle;
            protected int cantidad;
            protected int valorUnitario;
            protected int neto;

            /**
             * Gets the value of the numero property.
             * 
             */
            public int getNumero() {
                return numero;
            }

            /**
             * Sets the value of the numero property.
             * 
             */
            public void setNumero(int value) {
                this.numero = value;
            }

            /**
             * Gets the value of the detalle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDetalle() {
                return detalle;
            }

            /**
             * Sets the value of the detalle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDetalle(String value) {
                this.detalle = value;
            }

            /**
             * Gets the value of the cantidad property.
             * 
             */
            public int getCantidad() {
                return cantidad;
            }

            /**
             * Sets the value of the cantidad property.
             * 
             */
            public void setCantidad(int value) {
                this.cantidad = value;
            }

            /**
             * Gets the value of the valorUnitario property.
             * 
             */
            public int getValorUnitario() {
                return valorUnitario;
            }

            /**
             * Sets the value of the valorUnitario property.
             * 
             */
            public void setValorUnitario(int value) {
                this.valorUnitario = value;
            }

            /**
             * Gets the value of the neto property.
             * 
             */
            public int getNeto() {
                return neto;
            }

            /**
             * Sets the value of the neto property.
             * 
             */
            public void setNeto(int value) {
                this.neto = value;
            }

        }

    }

}
